# Console de acesso H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do banco de dados
spring.datasource.url=jdbc:h2:mem:testedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Criar e popular as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração da chave
api.security.token.secret=my-secret-key

#Configuração das imagens
upload.dir = upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#DEBUGs
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG

# Para ver as exceções de validação
logging.level.org.springframework.validation=DEBUG

# Habilitar access log do Tomcat (útil para ver status HTTP)
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b
server.tomcat.accesslog.directory=logs
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd

