# Console de acesso H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configura��o do banco de dados
spring.datasource.url=jdbc:h2:mem:testedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Criar e popular as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configura��o da chave
# api.security.token.secret=my-secret-key
api.security.token.secret=${JWT_SECRET:my-secret-key-my-secret-key-12345}

#Configura��o das imagens
upload.dir = upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#DEBUGs
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG

# Para ver as exce��es de valida��o
auth.microservice.url=http://localhost:8081

# N�veis de log
logging.level.com.example.crudObsidiana=DEBUG
logging.level.AUDIT=INFO
logging.level.SECURITY=WARN

# Arquivos de log separados
logging.file.name=logs/application.log
logging.file.path=logs

# Formato com timestamp
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ROTA��O de logs
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.max-file-size=10MB

# Para ver as exce��es de valida��o
logging.level.org.springframework.validation=DEBUG

# Habilitar access log do Tomcat (�til para ver status HTTP)
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b
server.tomcat.accesslog.directory=logs
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd