# Console de acesso H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do banco de dados
spring.datasource.url=jdbc:h2:mem:testedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Criar e popular as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração da chave
api.security.token.secret=my-secret-key

#Configuração das imagens
upload.dir = upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
